name: tronswan
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
  build_command: yarn install --frozen-lockfile && yarn build
  run_command: npx serve -s build -l 3000
  envs:
  - key: NODE_VERSION
    value: 20
  - key: NODE_ENV
    value: production
  - key: REACT_APP_API_KEY
    value: ${REACT_APP_API_KEY}
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xs 