name: tronswan
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
  build_command: yarn install --frozen-lockfile && yarn build
  run_command: node server.js
  envs:
  - key: NODE_VERSION
    value: 20
  - key: NODE_ENV
    value: production
  - key: VITE_API_KEY
    value: ${VITE_API_KEY}
  - key: VITE_CITY
    value: Bozeman
  - key: VITE_UNITS
    value: imperial
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs 