name: Test Coverage Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          
      - name: Install Yarn
        run: npm install -g yarn
        
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Run tests with coverage
        run: yarn test --coverage --watchAll=false --coverageReporters=text --coverageReporters=lcov --coverageReporters=html
        
      - name: Extract coverage percentage
        id: coverage
        run: |
          COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "Coverage: $COVERAGE%"
          
      - name: Update README with coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          # Update the coverage badge in README.md
          sed -i "s/\[!\[Test Coverage\].*\]/\[![Test Coverage\](https:\/\/img.shields.io\/badge\/coverage-${COVERAGE}%25-brightgreen)\]/" README.md
          
          # Update the coverage percentage in the Testing section
          sed -i "s/\*\*Current Coverage\*\*: [0-9.]*%/\*\*Current Coverage\*\*: ${COVERAGE}%/" README.md
          
      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update coverage badge to ${COVERAGE}%"
          git push
