name: Node.js CI and Deployment Status Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  check-deployment:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Poll Deployment Status
        run: |
          RETRIES=60 # Set this to the number of retries you are willing to make
          SLEEP_DURATION=10 # Set this to how long you want to wait between each retry
          DEPLOYMENT_STATUS="unknown"
          APP_ID="0513ce4c-b074-4139-bb38-a1c6a5bc97a6"
          DIGITALOCEAN_ACCESS_TOKEN="${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"
          echo "Polling DigitalOcean App Platform deployment status..."
          for ((i=1;i<=RETRIES;i++)); do
            DEPLOYMENT_STATUS=$(curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" \
              "https://api.digitalocean.com/v2/apps/$APP_ID/deployments" | jq -r '.deployments[0].progress')
            echo "Attempt $i: Deployment status is $DEPLOYMENT_STATUS"
            if [ "$DEPLOYMENT_STATUS" == "100" ]; then
              echo "Deployment completed successfully."
              break
            fi
            if [ $i -eq $RETRIES ]; then
              echo "Deployment did not complete after $RETRIES attempts."
              exit 1
            fi
            sleep $SLEEP_DURATION
          done
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Run Playwright Tests
        if: env.DEPLOYMENT_STATUS == '100'
        run: |
          echo 'Running Playwright tests...'
          echo 'TODO: Add your Playwright test command here.'
